import Head from 'next/head'
import Announcements from '../src/Components/Announcements'
import Nav from '../src/Components/Nav'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <Announcements />
        <Nav />
z      </Head>
    </div>
  )
}
