import Head from 'next/head'
import Announcements from '../src/Components/Announcements'
import Nav from '../src/Components/Nav'
import HomePage from '../src/Components/HomePage'
import Main from '../src/Components/Main'
import Category from '../src/Components/Category'
import Body from '../src/Components/Body'
import BookItem from '../src/Components/BookItem'
import Filter from '../src/Components/Filter'
import About from '../src/Components/About'
import Newsletter from '../src/Components/Newsletter'
import Footer from '../src/Components/Footer'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      </Head>

      <Announcements />
        <Nav />
        <HomePage />
        <Main />
        <Category />
        <Body />
        <BookItem />
        <Filter />
        <About />
        <Newsletter />
        <Footer />
        

    </div>
    
  )
}
